apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: awb-tests
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: quay.io/walidabouali/react-app
          ports:
            - containerPort: 8080
---
    apiVersion: v1
    kind: Service
    metadata:
      name: react-app
      namespace: awb-tests
    spec:
      selector:
        app: react-app
      ports:
        - name: react-port
          protocol: TCP
          port: 8080
          targetPort: 8080
---
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: react-app
      namespace: awb-tests
    spec:
      path: /
      to:
        kind: Service
        name: react-app
      port:
        targetPort: react-port
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: react-app
      namespace: awb-tests
    data:
      envName: dev
            